### ISSUE TITLE
Thunderbird 68 support

### ISSUE THREAD

**Issue by 532910** [acabal/thunderbird-addons#3]
Please add support for thunderbird 68

**Comment by acabal** [comment]
Pull requests welcomed!

**Comment by Solwayuk** [comment]
please update for thundebird 68+

tried to get them to add support for this hide feature. but kinda hit a wall.
https://bugzilla.mozilla.org/show_bug.cgi?id=1579124

**Comment by acabal** [comment]
I personally won't be upgrading to TB 68 for quite a while; and the last serious work I did on these addons was 5+ years ago, so I don't remember a whole lot about the process or the internals.

If you need TB 68 support ASAP, then I'm going to need help to do that. Pull requests are welcomed! The addons are fairly simple it shouldn't be *too* hard to figure things out. Otherwise, you're going to be waiting a really long time, unfortunately.

**Comment by 532910** [comment]
I set `user_pref("mail.accountmanager.localfoldersserver", "server1");` in my `user.js` and I don't see local folders more. http://howto.gumph.org/content/removing-local-folders-from-thunderbird/

**Comment by tooomm** [comment]
I really like to see the "Hide Local Folders" add-on to be updated, too! 👍 
Dealing with .js files, knowing the right options and tweaking them is just a mess for ordinary users.

**Comment by Qrzysio** [comment]
I have already tried to study WebExtensions docs. The first few tries came with no success, even add-ons are not so complicated.

**Comment by Solwayuk** [comment]
https://developer.thunderbird.net/add-ons/updates
start here?

**Comment by Qrzysio** [comment]
yeah, old extensions are "bootstraped" so the first step is here: https://developer.thunderbird.net/add-ons/updates/bootstrapped

**Comment by GaVenga** [comment]
A working workaround:

https://www.thunderbird-mail.de/forum/thread/82781-lokaler-ordner-ausblenden/

https://www.thunderbird-mail.de/attachment/10498-hide-local-folders-1-05a-tb-xpi/

**Comment by tooomm** [comment]
>yeah, old extensions are "bootstraped" so the first step is here: https://developer.thunderbird.net/add-ons/updates/bootstrapped

@Qrzysio Are you sure that the old extensions from Alex (like hide local folders) are „bootstrapped“ and not „overlay“ extensions?

Because the workaround that got posted above converts the extension in a way that considers it an „overlay“ one now. It might be wrong though.

I can’t tell where to look to distinguish both types for sure...

**Comment by Qrzysio** [comment]
I'm not an expert, but according to the docs, it is a bootstrapped extension.

> Uses a bootstrap file (`bootstrap.js`) as an entry point to the extension. The file defines four methods (`install`, `uninstall`, `startup`, and `shutdown`) from which all extension behaviour is controlled. This type of extension can be installed or shut down without restarting Thunderbird, so it’s sometimes called a “restartless” extension. Also uses an RDF manifest (`install.rdf`).

Source: https://developer.thunderbird.net/add-ons/about-add-ons#legacy-extensions

I have tried to create the `manifest.json` and follow the basic steps to upgrade one of these extensions. Unfortunately, no luck.

**Comment by tooomm** [comment]
I couldn't find such a `bootstrap.js` file in the "hide local folders" folder in this repo.
Also, the install.rtf has no `<em:bootstrap>true</em:bootstrap>` line.

>I have tried to create the manifest.json and follow the basic steps to upgrade one of these extensions. Unfortunately, no luck.

Did you try the version in my PR #5?

**Comment by Qrzysio** [comment]
You are right. I was working with "mark-gmail-read" extensions. Now I see they are all bootstrapped, except "hide-local-folders". I haven't tested it.

**Comment by tooomm** [comment]
@Qrzysio Did you get the other, bootstrapped addons to work with TB68 as well?
I guess @acabal is happy if you create a PR for them, too!

**Comment by Qrzysio** [comment]
Hi,
I work with the mark folder read extension. Unfortunately doing the basis like creating `manifest.json` is not enough. I will try to put some code here and focus more on that.

**Comment by tooomm** [comment]
In case you did not find this document yet, maybe it helps: https://developer.thunderbird.net/add-ons/tb68/bootstrapped

@acabal Can you reopen this ticket please until all extension are updated?

**Comment by GaVenga** [comment]
*****************
* ATTENTION:   *
*****************
if you have installed the (Test) version 2.0a made by tooomm:
remove this before installing the version of Alex!!!!!!!!!!!!!!!!!!!!!!!!!!

otherwise Thunderbird will not start.
On Linux:
remove the entry "hide-local-folders@alexcabal.com.xpi"
in: .thunderbird/(your profile)/extensions/

Thereafter the version from "https://addons.thunderbird.net/de/thunderbird/addon/hide-local-folders/"
works as expected...

Inzwischen leider zurückgezogen.
If you like to frikkel:
https://github.com/acabal/thunderbird-addons/pull/10

**Comment by tooomm** [comment]
#9 deals with compatibility for `Mark GMail read`
