### ISSUE TITLE
Local Folder sometimes appears again

### ISSUE THREAD

**Issue by tooomm** [acabal/thunderbird-addons#8]
With version 2.0 the addon works again, but as described in the german post (https://www.thunderbird-mail.de/forum/thread/82781-lokaler-ordner-ausblenden/?postID=449334#post449334) the "Local Folders" entry might appears again.

For me it happened once after several days that Thunderbird was running constantly and I only put the laptop to sleep at night. Restarting Thunderbird fixes it, but sometimes you also have to disable and re-enable the add-on again or a combination.
I'll watch out for more details and try version 68.2.1 of Thunderbird.

Thunderbird 68.2.0
Windows 10

**Comment by acabal** [comment]
Looks like this is a serious bug, see the reviews: https://addons.thunderbird.net/en-US/thunderbird/addon/hide-local-folders/

I'm disabling version 2.0 on the addons site until we can get this fixed.

**Comment by tooomm** [comment]
For me the situation is different and restarting the client does not break the extension as described in the reviews. In fact it has been running without issues for a while now.

Just restarted Thunderbird to test it.
When I startup the client I see the `Local folders` entry for ~2s and then it disappears.

**Comment by GaVenga** [comment]
Version 2.0 works for me flawlessly on Thunderbird 68.2.2
The only Problem was to **install** version 2.0 -
because I had not removed an older Version. After that it runs o.k. since some weeks
and: never the "Local Folders" entry appears again.
If I  disable the extension: Local Folders are shown after restarting TB
If I activate the extension: Local folders are hidden after restarting TB.
--  As expected. --

**Comment by tooomm** [comment]
I had another problem with a differnt addon, and I got told to run
**"thunderbird.exe -purgecaches"** to clear cached code from former addon versions.
I don't realize the delayed folder hide anymore, it correctly doesn't show up right from the beginning now.

Maybe there was a cache conflict, or a Thunderbird update fixed something.

**Comment by GaVenga** [comment]
**Maybe there was a cache conflict**
!
I think this is correct!!!

**Comment by ghost** [comment]
Adding -purgecaches commandline does indeed make the addon work as expected. As soon as I remove the commandline option again the Local Folders also appears again. So I'm going to use it as a workaround for now, it's obviously not ideal though. Considering the cache is javascript cache, it's probably not actually directly related to the addon bug but rather a fortunate side effect, essentially making it behave as though the addon was just installed for the first time.

**Comment by tooomm** [comment]
Hmm, I only used the command once.

**Comment by acabal** [comment]
Marcus Loeffler has submitted a patch that should fix this issue.

Can you build from this branch and test it on your machines: https://github.com/acabal/thunderbird-addons/pull/10

If possible please test if for a week and let's see if this branch fixes the issue.

**Comment by WildByDesign** [comment]
@acabal  This patch from Marcus Loeffler seems to be working great on my end for several days now. The fix is working and consistent as well.

The only odd thing is that Thunderbird displays the Local Folders in the pane for literally a split-second before it disappears. Although this minor split-second glitch is much better in comparison.

**Comment by acabal** [comment]
Fixed by #10

**Comment by ghost** [comment]
Do you know when the update will appear on mozilla addons?

**Comment by acabal** [comment]
It's in their review queue now, it's up to them to approve it.

**Comment by ghost** [comment]
Excellent, thank you.
